packaging_format = 2

id = "xnbtd"
name = "xNBTD"
description.en = "Digital signage system for high schools"
description.fr = "Affichage dynamique open-source pour les lycées"

version = "0.0.6~ynh1"

maintainers = ["eldertek"]

[upstream]
license = "GPL-3.0"
website = "https://github.com/eldertek/xnbtd"
admindoc = "https://github.com/eldertek/xnbtd_ynh"
userdoc = "https://github.com/eldertek/xnbtd"
code = "https://github.com/eldertek/xnbtd_ynh"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "250M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, xnbtd will be accessible by users without a YunoHost account. This can be changed later in the webadmin."
    help.fr = "Si cette case est cochée, xnbtd sera accessible par les utilisateurs n’ayant pas de compte YunoHost. Vous pourrez changer cela dans la webadmin."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    
    [resources.data_dir]
    group = "xnbtd:wrx"
    
    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ""

    [resources.database]
    type = "postgresql"